# Generated by Django 3.1.8 on 2021-08-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210826_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='Click the link above to read the blog post', max_length=255),
        ),
    ]
