# Generated by Django 3.1.8 on 2021-12-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20211127_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(default='Click the link below to read the blog post..', max_length=255),
        ),
    ]
